// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG_mwLvUmms0DVtuLb0OLBjHeTLbavDcI',
    appId: '1:11681816949:web:3aee46e4ce63dc891af33c',
    messagingSenderId: '11681816949',
    projectId: 'quiz-app-4ff0b',
    authDomain: 'quiz-app-4ff0b.firebaseapp.com',
    storageBucket: 'quiz-app-4ff0b.firebasestorage.app',
    measurementId: 'G-05QEZGKJEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuEa3mZ55Xe061gCUY8OOzfUGMi6-A80s',
    appId: '1:11681816949:android:9a834705e4f5de591af33c',
    messagingSenderId: '11681816949',
    projectId: 'quiz-app-4ff0b',
    storageBucket: 'quiz-app-4ff0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlLZC8NoG-FpTvqASo9Z7v6LWvLujJV1o',
    appId: '1:11681816949:ios:2002fb659fc3373c1af33c',
    messagingSenderId: '11681816949',
    projectId: 'quiz-app-4ff0b',
    storageBucket: 'quiz-app-4ff0b.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlLZC8NoG-FpTvqASo9Z7v6LWvLujJV1o',
    appId: '1:11681816949:ios:2002fb659fc3373c1af33c',
    messagingSenderId: '11681816949',
    projectId: 'quiz-app-4ff0b',
    storageBucket: 'quiz-app-4ff0b.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG_mwLvUmms0DVtuLb0OLBjHeTLbavDcI',
    appId: '1:11681816949:web:ad6d2663d109d5d91af33c',
    messagingSenderId: '11681816949',
    projectId: 'quiz-app-4ff0b',
    authDomain: 'quiz-app-4ff0b.firebaseapp.com',
    storageBucket: 'quiz-app-4ff0b.firebasestorage.app',
    measurementId: 'G-L5Y6HSJVQG',
  );
}
